name: Add Timestamp

on:
  push:
    paths:
      - '_data/input.json'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup jq
      uses: sergeysova/jq-action@v2

    - name: Add timestamp
      run: |
        pwd
        ls
        timestamp=$(date +%s)
        jq --arg timestamp $timestamp '. + {timestamp: $timestamp}' json/menu.json > output.json
      env:
        timestamp: ${{ env.timestamp }}

    - name: Upload output
      uses: actions/upload-artifact@v2
      with:
        name: output.json
        path: _data/output.json
